### PR TITLE
French translation. Done!

### PR DESCRIPTION
**Pull request by manekinekko**
My contribution to issue https://github.com/mgechev/angularjs-in-patterns/issues/20

### CODE REVIEW

**Comment by mgechev** [comment]
Awesome! Thank you for the translation! I'll update the github page tomorrow.

**Comment by manekinekko** [comment]
You're welcome. Do you allow me to use some parts in my blog (images too)?

**Comment by mgechev** [comment]
Sure, you're welcome to do so. You can share link to the original post somewhere.

**Comment by manekinekko** [comment]
Perfect. I will link to ur repo. thx.

**Pull request merged**
