### PR TITLE
updated observer pattern for modern angular style guide and added examples

### PR DESCRIPTION
**Pull request by greglbd**

### CODE REVIEW

**Comment by mgechev** [comment]
I agree with this practice, it fits great with controllerAs. Right now, with the changes applied, the observer pattern is not in the correct section of the document, since it is in section scope, although an external service is used instead of `$scope.$on`, `$scope.$emit`, etc.
However, I started [refactoring of the document](https://github.com/mgechev/angularjs-in-patterns/tree/m-ng2) in order to include some additional patterns from Angular 2, so the entire structure of the document will change.

Since I am not sure when I'll find enough time to include the Angular 2 part, I'd suggest you to add the observer pattern, implemented with external service, to the "Others" section and leave the current description in the "Scope" section (just as it is now). Since this document doesn't describe only best practices, I think mentioning the old-fashioned way of publish/subscribe is not an issue.

**Comment by greglbd** [comment]
@mgechev that sounds good to me.  What would you like the title to be "Observer pattern as external service"?
Can i suggest that in the current observer pattern section I put an internal link to the "Observer pattern as external service" as using a controllerAs is best practice.

**Comment by mgechev** [comment]
Yes, sounds great!

**Comment by greglbd** [comment]
@mgechev reorganised, let me know if you'd like anything else changed?

**Comment by mgechev** [comment]
Thanks!

**Comment by mgechev** [comment]
I did some changes. You can find [them here](https://github.com/mgechev/angularjs-in-patterns/commit/eb08af67dab7258ede074ecd38c265c40a39c811).

It wasn't necessary to publish the entire interface of your service, since the repository doesn't aim to promote any external library it **only** states the usage of design patterns inside AngularJS and AngularJS based applications.

**Comment by greglbd** [comment]
Perfect.  fits in well.

**Pull request merged**
